import 'package:flutter/material.dart';

final Map<String, Color> depthColors = {
  'LANDA': Colors.blue,
  'DEPVS': Colors.green,
  'DEPMS': Colors.purple,
  'DEPMD': Colors.yellow,
  'LAN2DA': Colors.blue,
  'DEP11VS': Colors.green,
  'DEPM2S': Colors.purple,
  'DEPM1D': Colors.yellow,
  'LA6N2DA': Colors.blue,
  'DE1P4VS': Colors.green,
  'DEP5MS': Colors.purple,
  'DE1PMD': Colors.yellow,
  '1LANDA': Colors.blue,
  'D2EPVS': Colors.green,
  'D3EPMS': Colors.purple,
  'DEP4MD': Colors.yellow,
  'LAN52DA': Colors.blue,
  'DEP161VS': Colors.green,
  'DEPM782S': Colors.purple,
  'DEPM19D': Colors.yellow,
  'LA6N290DA': Colors.blue,
  'DE1P4V123S': Colors.green,
  'DEP5M512S': Colors.purple,
  'DE1PMD2': Colors.yellow,
};
